name: Deploy to Raspberry Pi

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Restart service
        run: |
          sudo systemctl restart sloorjuice_dot_com.service
          sudo systemctl status sloorjuice_dot_com.service